### PR TITLE
Add option not to rely on quota

### PR DESCRIPTION
**Pull request by eugene-bright**
Now double `-e` (`-ee`) option imply `noQuota` mode.
In `noQuota` mode snapshot ordering is done by `otime` value.

### CODE REVIEW

**Comment by eugene-bright** [comment]
Currently it's tested only with btrfs -> btrfs transferring scenario.
A lot of ad-hoc solutions is made.

This patch is provided merely to demonstrate useful approach rather then for incorporation in master.
I've failed to tune `BestDiffs.analyse`to work without size information.

**Comment by ceremcem** [comment]
Such a critical workaround should be merged into master, IMHO.

**Comment by eugene-bright** [comment]
I'm sure it breaks a lot of other things.
But you can still give it a try.

**Comment by eugene-bright** [comment]
I've migrated to btrbk

**Pull request closed without merging**
