### PR TITLE
do not quota-rescan unless the user asks for it.

### PR DESCRIPTION
**Pull request by smoofra**
Quota-rescan is a really heavyweight operation and it shouldn't be done silently
without the user's knowledge or permission.  It can also take quite a long time
to complete.

### CODE REVIEW

**Comment by AmesCornish** [comment]
Thank for the PR.  I am currently out of town and will take a look at it when I'm back next week.

**Comment by AmesCornish** [comment]
I took a look at your patches.  I  agree with you that rescan is heavyweight and annoying.  Unfortunately, btrfs quotas are a bit buggy, and often end up giving corrupt sizes, which can cause buttersink to do some really heavyweight (and unnecessary) transfers.  Buttersink needs quota turned on to get size estimates to pick reasonable diffs to transfer.  The right thing to do is to (which is currently the buttersink behavior), is to turn on quotas the first time you use buttersink, and then to rescan if the quota estimates become corrupt (e.g. returning estimates of many Terabytes for small snapshots).

I think it's very important that the default behavior, with no arguments, provide good results.  I am open to prompting the user for confirmation (if we verify that a user is present, and we're not being run in a cron job) before doing a rescan.  I'm also open to providing a flag that would prevent a rescan.  If buttersink detects that a rescan is necessary, but the user flag has disallowed it, it would have to error out, or possibly try to continue with some alternate way of guessing at snapshot sizes.

If you're willing to take a stab at one of the above approaches, that would be great!  If not, I'll probably look at them myself before too long.

Thanks for your contribution!

**Comment by eugene-bright** [comment]
Snapshots deletions while quota is enabled do cause critical disk io starvation on my system. See issue #38.
@AmesCornish, would simple snapshot sorting by time give good enough results for incremental transfer?

**Comment by eugene-bright** [comment]
Thanks for this PR!

I'm currently working on backward compatible approach to disable quotas.
It's based on your work.
https://github.com/eugene-bright/buttersink/tree/no-quota

As work will be done this request will be superseded.

**Comment by AmesCornish** [comment]
Duplicate of #60

**Pull request closed without merging**
